### ISSUE TITLE
Adventure card info mixed with Complication info

### ISSUE THREAD

**Issue by petbod-lm** [wargfn/travellerdb#1]
looking at Adventure cards I see that the traits and flavor text for the Contract appear below the Complication information

**Comment by petbod-lm** [comment]
When trying to download one of my decks to a text file I get the following exception:

Variable "characters" does not exist.
500 Internal Server Error - Twig_Error_Runtime

Stack Trace
in src/AppBundle/Resources/views/Export/plain.txt.twig at line 27   -
{% set conns = deck.slots_by_type.conn %}
Connection Card{% if **characters**|length > 1 %}s{% endif %}
{% for slot in conns %}
{{ slot.quantity }}x {{ slot.card.name }} ({{ slot.card.pack.name }})

[This is only the first part of the stack trace]

**Comment by wargfn** [comment]
Adding this to the group for Card Modale Display issues.

**Comment by wargfn** [comment]
The card Modal Data as has been updated for both the Pop-up screen and the Card Modal pages.  Staging file push into production.  Will Push once the card display pages are finished being updated.

**Comment by wargfn** [comment]
Card Display Data has been adjusted.
