### ISSUE TITLE
Internal Server Error when downloading a deck to text file

### ISSUE THREAD

**Issue by petbod-lm** [wargfn/travellerdb#2]
When trying to download one of my decks to a text file I get the following exception:

Variable "characters" does not exist.
500 Internal Server Error - Twig_Error_Runtime

Stack Trace
in src/AppBundle/Resources/views/Export/plain.txt.twig at line 27 -
{% set conns = deck.slots_by_type.conn %}
Connection Card{% if characters|length > 1 %}s{% endif %}
{% for slot in conns %}
{{ slot.quantity }}x {{ slot.card.name }} ({{ slot.card.pack.name }})

[This is only the first part of the stack trace]

**Comment by wargfn** [comment]
Resolved lingering Character issue. Exports now producing the intended plain text file with a card listing in it. Similiar to below:

Buccaneer Beowulf

Beowulf Free Trader Ship


Packs: From Beowulf Free Trader Ship (2) to Trouble on the Mains

Adventure Cards
2x Down the Main (Beowulf Free Trader Ship)
1x Humanitarian Evacuation (Beowulf Free Trader Ship)
1x Mid Passage Mark (Beowulf Free Trader Ship)
1x Universal World Profile Update (Type S Scout Ship)
1x X-Boat Route Review (Type S Scout Ship)
1x Corporate Contraband (Empress Marava Far Trader Ship)
2x In the Presence of Mine Enemies (Empress Marava Far Trader Ship)
2x Showing the Flag (Empress Marava Far Trader Ship)
1x TAS Inspection (Empress Marava Far Trader Ship)
2x The Asylum Seeker (Subsidized Merchant Ship)
1x The Baron's Tour (Subsidized Merchant Ship)
1x Better Supply Run (Subsidized Merchant Ship)
2x Tag and Bag (Subsidized Merchant Ship)
1x The Traveling Saleswoman (Subsidized Merchant Ship)
1x Interspecies Census (Aliens of the Imperium)


Connection Cards
1x Crazy Eddy's Discount Depot (Beowulf Free Trader Ship)
1x Biddable Official (Subsidized Merchant Ship)
2x Black Market Investors (Trouble on the Mains)
2x Rhal'Kais Chop Shop (Trouble on the Mains)

Crew Cards
1x Jim Thorne (Beowulf Free Trader Ship)
2x Rika Honami (Beowulf Free Trader Ship)
1x Marta Rodriguez (Empress Marava Far Trader Ship)
1x Sir Cynewulf Jauregg (Empress Marava Far Trader Ship)
1x Walter Green, IMC (ret) (Subsidized Merchant Ship)
1x Dezihdhodhude Mehro (Aliens of the Imperium)
1x Gorbash (Aliens of the Imperium)
1x Kydut Naboh (Aliens of the Imperium)
1x Liach, T'zen and Giiar (Aliens of the Imperium)
2x Gvaerrggoursu (Trouble on the Mains)

Gear Cards
1x Armed Gig (Beowulf Free Trader Ship)
1x Fragmentation Grenade (Beowulf Free Trader Ship)
1x Panacea Autoinjector (Beowulf Free Trader Ship)
1x Neural Gun (Empress Marava Far Trader Ship)
2x Xenopoison (Empress Marava Far Trader Ship)
2x TL-13 CLC Laser Rifle (Subsidized Merchant Ship)
3x Alien Pathogen (Trouble on the Mains)
1x Realms of Rampage (Trouble on the Mains)

Events
2x Just a Little Longer... (Type S Scout Ship)
3x Predatory Tactics (Type S Scout Ship)
1x Alien Persecution (Aliens of the Imperium)
1x Homesick (Trouble on the Mains)
3x Trouble on the Mains (Trouble on the Mains)

Heroic Events
3x Dance Among the Heavens  (Empress Marava Far Trader Ship)
3x Aggravated Assualt  (Trouble on the Mains)
1x Prey on the Weak  (Trouble on the Mains)
2x Sinister Reputation  (Trouble on the Mains)

Upgrades
3x Missile Barbette  (Beowulf Free Trader Ship)
2x False Registry Markings  (Type S Scout Ship)
2x RVD Overtuned Thruster Plate  (Type S Scout Ship)
2x Tactical Display  (Empress Marava Far Trader Ship)
1x Dreaded Visage  (Trouble on the Mains)
1x Hacker's Chainsaw  (Trouble on the Mains)

**Comment by petbod-lm** [comment]
Fantastic.  Thanks for the quick update
