### ISSUE TITLE
Distance value not displayed for Contract

### ISSUE THREAD

**Issue by petbod-lm** [wargfn/travellerdb#3]
Would it be possible to add the Distance for a contract to the Adventure card information?

**Comment by wargfn** [comment]
Adding this to the group for Card Modale Display issues.

**Comment by wargfn** [comment]
The card Modal Data as has been updated for both the Pop-up screen and the Card Modal pages.  Staging file push into production.  Will Push once the card display pages are finished being updated.

**Comment by wargfn** [comment]
Card Display Data has been adjusted.
