### ISSUE TITLE
Internal Server Error when downloading a deck to octgn file

### ISSUE THREAD

**Issue by petbod-lm** [wargfn/travellerdb#4]
When I try to download one of my decks in octgn format I get the following exception:

Key "plot" for array with keys "adv, conn, crew, event, gear, heroic, upgrade" does not exist.
500 Internal Server Error - Twig_Error_Runtime

Stack Trace
in src/AppBundle/Resources/views/Export/octgn.xml.twig at line 12   -
{% endfor %}
  </section>
  <section name="Plots" shared="False">
{% for slot in deck.slots_by_type.plot %}
    <card qty="{{ slot.quantity }}" id="{{ slot.card.octgnId }}">{{ slot.card.name }}</card>
{% endfor %}
  </section>

**Comment by wargfn** [comment]
I dressed up the OCTGN export. It is still failing due to none of the cards having an OCTGN ID that I am aware of. If the game is on OCTGN, be more than happy to index the card IDs and assign them in the database and re-enable export.
