### ISSUE TITLE
Expense value not displayed for Connection

### ISSUE THREAD

**Issue by petbod-lm** [wargfn/travellerdb#6]

**Comment by wargfn** [comment]
Adding this to the group for Card Modale Display issues.

**Comment by wargfn** [comment]
The card Modal Data as has been updated for both the Pop-up screen and the Card Modal pages.  Staging file push into production.  Will Push once the card display pages are finished being updated.

**Comment by wargfn** [comment]
Cost / Expense / Subtype / Textbox all displaying correctly in Modals and Card pages now.
